# Examples

# POD v1
# Service v1
# ReplicaSet apps/v1
# Deployment apps/v1

# $ kubectl create -f this-file.yml
# $ kubectl get pods
# $ kubectl describe pod app-name-pod

# POD Example
# Kubernetes API Version 
apiVersion: v1
# POD|Service|ReplicaSet|Deploymnet|
kind: Pod

# Name and Labels
# labels can be anything key/value (frontend|backend|database|etc)
metadata:
 name: app-name-pod
 labels:
   app: app-name 
   key: value

# The thing we're creating, correct format needed.
# For a single container, it's simple.
spec:
 containers:
   - name: nginx-container
     image: nginx


# kubectl create -f rc-description.yml
# kubectl get replicationcontroller 
## ReplicationControler v1
apiVersion: v1
kind: ReplicationController
metadata:
 name: app-name-rc
 labels:
   app: app-name
   key: value

spec:
  template:
    # Nested from the POD yml
    metadata:
     name: app-name-pod
     labels:
       app: app-name
       key: value
    spec:
     containers:
       - name: nginx-container
         image: nginx
  replica: 3
